#!/bin/bash  

SDK_VERSION=6.0
xcodebuild -configuration Release -target "CloudKit" -sdk iphoneos$SDK_VERSION ARCHS="armv7 armv7s"
xcodebuild -configuration Release -target "CloudKit" -sdk iphonesimulator$SDK_VERSION ARCHS="i386"
